<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
<!--#if (postgres) -->
    <PackageReference Include="Deedbox.Postgres" Version="DEEDBOX_VERSION" />
<!--#else -->
    <PackageReference Include="Deedbox.SqlServer" Version="DEEDBOX_VERSION" />
<!--#endif -->
  </ItemGroup>
</Project>
