<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Postgres provider for Deedbox.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Deedbox/Deedbox.csproj" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Deedbox.Cli" />
    <InternalsVisibleTo Include="Deedbox.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Schema/*.sql" LogicalName="Deedbox.Postgres.Schema.%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
