<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Deedbox/Deedbox.csproj" />
    <ProjectReference Include="../../src/Deedbox.Postgres/Deedbox.Postgres.csproj" />
    <ProjectReference Include="../../src/Deedbox.SqlServer/Deedbox.SqlServer.csproj" />
    <ProjectReference Include="../../src/Deedbox.EntityFrameworkCore/Deedbox.EntityFrameworkCore.csproj" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
</Project>
